-- AlterTable
ALTER TABLE "customer" ALTER COLUMN "address1" SET DEFAULT '',
ALTER COLUMN "address2" SET DEFAULT '',
ALTER COLUMN "city" SET DEFAULT '',
ALTER COLUMN "state" SET DEFAULT '',
ALTER COLUMN "zip" SET DEFAULT '',
ALTER COLUMN "country" SET DEFAULT 'US';
