services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-net
  next-app:
    container_name: next-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git
        - action: rebuild
          path: package.json
    # Set environment variables based on the .env file
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-net

volumes:
  db-data:
networks:
  app-net:
    driver: bridge
