import {
  EMPTY_STRING,
  DEFAULT_OPEN_TIME,
  DEFAULT_CLOSE_TIME,
} from "@/lib/consts";
import { z } from "zod";
import { LOCATION_TYPES_TYPE } from "@/features/locations/components/forms/LocationForm";

export const locationSchema = z.object({
  name: z.string().min(3),
  slug: z.string().min(4),
  nickname: z.string(),
  description: z.string(),
  phone: z.string(),
  email: z.string().email(),
  website: z.string(),
  x: z.string(),
  instagram: z.string(),
  facebook: z.string(),
  type: z.enum(["PHYSICAL", "MOBILE"]),
  address1: z.string(),
  address2: z.string(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
  id: z.string().optional(),
  requiresSurveyForBooking: z.boolean().optional(),
  monStart: z.string().optional(),
  monEnd: z.string().optional(),
  monClosed: z.boolean(),
  tueStart: z.string().optional(),
  tueEnd: z.string().optional(),
  tueClosed: z.boolean(),
  wedStart: z.string().optional(),
  wedEnd: z.string().optional(),
  wedClosed: z.boolean(),
  thuStart: z.string().optional(),
  thuEnd: z.string().optional(),
  thuClosed: z.boolean(),
  friStart: z.string().optional(),
  friEnd: z.string().optional(),
  friClosed: z.boolean(),
  satStart: z.string().optional(),
  satEnd: z.string().optional(),
  satClosed: z.boolean(),
  sunStart: z.string().optional(),
  sunEnd: z.string().optional(),
  sunClosed: z.boolean(),
});

export type LocationType = z.infer<typeof locationSchema>;

export const EMPTY_LOCATION_DATA: LocationType = {
  id: EMPTY_STRING,
  slug: EMPTY_STRING,
  name: EMPTY_STRING,
  nickname: EMPTY_STRING,
  description: EMPTY_STRING,
  phone: EMPTY_STRING,
  email: EMPTY_STRING,
  website: EMPTY_STRING,
  x: EMPTY_STRING,
  instagram: EMPTY_STRING,
  facebook: EMPTY_STRING,
  type: LOCATION_TYPES_TYPE["PHYSICAL"], // Default value; change if necessary
  address1: EMPTY_STRING,
  address2: EMPTY_STRING,
  city: EMPTY_STRING,
  state: EMPTY_STRING,
  zip: EMPTY_STRING,
  monStart: DEFAULT_OPEN_TIME,
  monEnd: DEFAULT_CLOSE_TIME,
  monClosed: false,
  tueStart: DEFAULT_OPEN_TIME,
  tueEnd: DEFAULT_CLOSE_TIME,
  tueClosed: false,
  wedStart: DEFAULT_OPEN_TIME,
  wedEnd: DEFAULT_CLOSE_TIME,
  wedClosed: false,
  thuStart: DEFAULT_OPEN_TIME,
  thuEnd: DEFAULT_CLOSE_TIME,
  thuClosed: false,
  friStart: DEFAULT_OPEN_TIME,
  friEnd: DEFAULT_CLOSE_TIME,
  friClosed: false,
  satStart: DEFAULT_OPEN_TIME,
  satEnd: DEFAULT_CLOSE_TIME,
  satClosed: true,
  sunStart: DEFAULT_OPEN_TIME,
  sunEnd: DEFAULT_CLOSE_TIME,
  sunClosed: true,
  requiresSurveyForBooking: false,
};
