-- AlterTable
ALTER TABLE "Location" ADD COLUMN     "friClosed" BOOLEAN DEFAULT false,
ADD COLUMN     "friEnd" TEXT DEFAULT '',
ADD COLUMN     "friStart" TEXT DEFAULT '',
ADD COLUMN     "monClosed" BOOLEAN DEFAULT false,
ADD COLUMN     "monEnd" TEXT DEFAULT '',
ADD COLUMN     "monStart" TEXT DEFAULT '',
ADD COLUMN     "satClosed" BOOLEAN DEFAULT false,
ADD COLUMN     "satEnd" TEXT DEFAULT '',
ADD COLUMN     "satStart" TEXT DEFAULT '',
ADD COLUMN     "sunClosed" BOOLEAN DEFAULT false,
ADD COLUMN     "sunEnd" TEXT DEFAULT '',
ADD COLUMN     "sunStart" TEXT DEFAULT '',
ADD COLUMN     "thuClosed" BOOLEAN DEFAULT false,
ADD COLUMN     "thuEnd" TEXT DEFAULT '',
ADD COLUMN     "thuStart" TEXT DEFAULT '',
ADD COLUMN     "tueClosed" BOOLEAN DEFAULT false,
ADD COLUMN     "tueEnd" TEXT DEFAULT '',
ADD COLUMN     "tueStart" TEXT DEFAULT '',
ADD COLUMN     "wedClosed" BOOLEAN DEFAULT false,
ADD COLUMN     "wedEnd" TEXT DEFAULT '',
ADD COLUMN     "wedStart" TEXT DEFAULT '';
