-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "address1" DROP NOT NULL,
ALTER COLUMN "address1" DROP DEFAULT,
ALTER COLUMN "address2" DROP NOT NULL,
ALTER COLUMN "address2" DROP DEFAULT,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "city" DROP DEFAULT,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "state" DROP DEFAULT,
ALTER COLUMN "zip" DROP NOT NULL,
ALTER COLUMN "zip" DROP DEFAULT;
